#!/usr/bin/env bash

# Install git if necessary
sudo apt-get install git

# Move into home directory
cd ~

# Make OpenFOAM directory
mkdir -p ~/OpenFOAM
cd ~/OpenFOAM

# Clone OpenFOAM
git clone git://github.com/OpenFOAM/OpenFOAM-2.4.x.git

# Obtain 3rd party libs
wget http://downloads.sourceforge.net/foam/ThirdParty-2.4.0.tgz

# Extract 3rd party libs
tar -xzvf ThirdParty-2.4.0.tgz
mv ThirdParty-2.4.0 ThirdParty-2.4.x
rm ThirdParty-2.4.0.gz

# Obtain some software
sudo apt-get install build-essential flex bison cmake zlib1g-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev 

sudo apt-get install qt4-dev-tools libqt4-dev libqt4-opengl-dev freeglut3-dev libqtwebkit-dev 

sudo apt-get install libscotch-dev libcgal-dev

# Source environmental variables
source $HOME/OpenFOAM/OpenFOAM-2.4.x/etc/bashrc

# Make OpenFOAM
cd $WM_PROJECT_DIR
./Allwmake

# Make ParaView
cd $WM_THIRD_PARTY_DIR
./makeParaView4

# Create a Foam Run directory
mkdir -p $FOAM_RUN 

# Copy tutorials
cp -r $FOAM_TUTORIALS $FOAM_RUN

# Append to bashrc
echo source $HOME/OpenFOAM/OpenFOAM-2.4.x/etc/bashrc >> ~/.bashrc
